### ISSUE TITLE
Node previews miss some whitespace between elements in Chrome

### ISSUE THREAD

**Issue by captainbrosset** [captainbrosset/devtools-highlighter#27]
It looks like nodes that are displayed in the output miss some whitespace between the tag name and attributes, and between attributes.

See below:
<img width="481" alt="space" src="https://user-images.githubusercontent.com/1152698/36585033-79fdf64a-187c-11e8-839b-fa70f4dbc6da.PNG">

This can probably be fixed very easily in CSS in this file: https://github.com/captainbrosset/devtools-highlighter/blob/master/src/devtools/panel/style.css

I'm guessing that for some reason, the whitespace works in Firefox because the display type is different. But I haven't investigated.

**Comment by kmongy** [comment]
Hi! @captainbrosset,

Full disclosure, I'm a total newb to github. Nonetheless, I believe I found where the issue lies. In Chrome, after some digging, I found that it was an issue with the span element. My current "fix" is setting the margin-right of the span to .5em. See the screenshot below to see how it looks:

![screen shot 2018-02-23 at 2 38 07 pm](https://user-images.githubusercontent.com/12740407/36615860-5822d7b8-18a7-11e8-9fc5-37b4369484c9.png)

Let me know if this close to what you're looking for.

**Comment by captainbrosset** [comment]
You are right, this is the right approach. Chrome is missing some margin while Firefox does have it.
The margin is there in the CSS code but is just not recognized by Chrome because I've used a CSS logical property for this which is only implemented in Firefox for now.

I was working on something related to this just now, and realized this while looking at the code. So I ended up fixing this at the same time. Sorry for stealing this, but I do have the fix ready, so I'll just push it!
